version: '3.9'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: quantumbci-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-quantumbci}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-admin}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - quantumbci-network

  # Streamlit Application
  streamlit:
    build: .
    container_name: quantumbci-app
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-password}@postgres:5432/${POSTGRES_DB:-quantumbci}
    volumes:
      # Mount for development (comment out for production)
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - quantumbci-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  quantumbci-network:
    driver: bridge
